In [77]:
import cv2
print("Imported")

Imported


In [78]:
img1 = cv2.imread("C:\\Users\\Ritchie\\Desktop\\ritchieprof.jpg",1)



In [79]:
print(type(img1))


<class 'numpy.ndarray'>


In [80]:
print(img1)

[[[14 16 16]
  [14 16 16]
  [14 16 16]
  ...
  [14 16 17]
  [14 16 17]
  [14 16 17]]

 [[14 16 16]
  [14 16 16]
  [14 16 16]
  ...
  [14 16 17]
  [14 16 17]
  [14 16 17]]

 [[14 16 16]
  [14 16 16]
  [14 16 16]
  ...
  [14 16 17]
  [14 16 17]
  [14 16 17]]

 ...

 [[17 19 20]
  [17 19 20]
  [17 19 20]
  ...
  [21 23 24]
  [20 22 23]
  [18 20 21]]

 [[17 19 20]
  [17 19 20]
  [17 19 20]
  ...
  [21 23 24]
  [20 22 23]
  [18 20 21]]

 [[17 19 20]
  [17 19 20]
  [17 19 20]
  ...
  [21 23 24]
  [20 22 23]
  [18 20 21]]]


In [69]:
cv2.imshow("Type your title here", img)
cv2.waitKey(0)
#cv2.waitKey(100)
cv2.destroyAllWindows()

In [70]:
resizedImg = cv2.resize(img, (int(img.shape[1]/2),int(img.shape[0]/2)))
cv2.imshow("Type your title here", resizedImg)
cv2.waitKey(0)
#cv2.waitKey(100)
cv2.destroyAllWindows()

In [ ]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
img1 = cv2.imread("C:\\Users\\Ritchie\\Desktop\\ritchieprof.jpg")
gray_img = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(gray_img, scaleFactor = 1.05, minNeighbors=5)
print(type(faces))
print(faces)
for x,y,w,h in faces:
    img1 = cv2.rectangle(img1, (x,y), (x+w,y+h), (0,255,0),3)
cv2.imshow("Face Detection System", img1)
cv2.waitKey()
cv2.destroyAllWindows()
    



<class 'numpy.ndarray'>
[[ 46 106 197 197]]
